package com.bloodbank.model;

// Generated Mar 16, 2013 12:03:45 PM by Hibernate Tools 3.3.0.GA

/**
 * AccountDetail generated by hbm2java
 */
public class AccountDetail implements java.io.Serializable {

	private Integer accountId;
	private UserDetail userDetail;
	private StaffDetail staffDetail;
	private String login;
	private String password;
	private String emailId;
	private String userType;

	public AccountDetail() {
	}

	public AccountDetail(UserDetail userDetail, StaffDetail staffDetail,
			String login, String password, String emailId, String userType) {
		this.userDetail = userDetail;
		this.staffDetail = staffDetail;
		this.login = login;
		this.password = password;
		this.emailId = emailId;
		this.userType = userType;
	}

	public Integer getAccountId() {
		return this.accountId;
	}

	public void setAccountId(Integer accountId) {
		this.accountId = accountId;
	}

	public UserDetail getUserDetail() {
		return this.userDetail;
	}

	public void setUserDetail(UserDetail userDetail) {
		this.userDetail = userDetail;
	}

	public StaffDetail getStaffDetail() {
		return this.staffDetail;
	}

	public void setStaffDetail(StaffDetail staffDetail) {
		this.staffDetail = staffDetail;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	public String getUserType() {
		return this.userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

}
