package com.bloodbank.model;

// Generated Mar 16, 2013 12:03:45 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * CommentDetail generated by hbm2java
 */
public class CommentDetail implements java.io.Serializable {

	private Integer commentId;
	private UserDetail userDetail;
	private EventDetail eventDetail;
	private String commentDetail;
	private Date commentDate;
	private String commentTime;

	public CommentDetail() {
	}

	public CommentDetail(UserDetail userDetail, EventDetail eventDetail,
			String commentDetail, Date commentDate, String commentTime) {
		this.userDetail = userDetail;
		this.eventDetail = eventDetail;
		this.commentDetail = commentDetail;
		this.commentDate = commentDate;
		this.commentTime = commentTime;
	}

	public Integer getCommentId() {
		return this.commentId;
	}

	public void setCommentId(Integer commentId) {
		this.commentId = commentId;
	}

	public UserDetail getUserDetail() {
		return this.userDetail;
	}

	public void setUserDetail(UserDetail userDetail) {
		this.userDetail = userDetail;
	}

	public EventDetail getEventDetail() {
		return this.eventDetail;
	}

	public void setEventDetail(EventDetail eventDetail) {
		this.eventDetail = eventDetail;
	}

	public String getCommentDetail() {
		return this.commentDetail;
	}

	public void setCommentDetail(String commentDetail) {
		this.commentDetail = commentDetail;
	}

	public Date getCommentDate() {
		return this.commentDate;
	}

	public void setCommentDate(Date commentDate) {
		this.commentDate = commentDate;
	}

	public String getCommentTime() {
		return this.commentTime;
	}

	public void setCommentTime(String commentTime) {
		this.commentTime = commentTime;
	}

}
