package com.bloodbank.model;

// Generated Apr 16, 2013 7:17:24 PM by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

/**
 * DonorDetail generated by hbm2java
 */
public class DonorDetail implements java.io.Serializable {

	private Integer donorId;
	private ContactDetail contactDetail;
	private String bloodGroup;
	private Integer donatedTimes;
	private String isSpecialDonor;
	private String donationDate;
	private String donorRandomId;
	private Integer weight;
	private String bloodPressure;
	private Integer pulse;
	private String hemoglobin;
	private Set<PatientDetail> patientDetails = new HashSet<PatientDetail>(0);
	private Set<BloodBottleDetail> bloodBottleDetails = new HashSet<BloodBottleDetail>(
			0);

	public DonorDetail() {
	}

	public DonorDetail(ContactDetail contactDetail, String bloodGroup,
			Integer donatedTimes, String isSpecialDonor, String donationDate,
			String donorRandomId, Integer weight, String bloodPressure,
			Integer pulse, String hemoglobin,
			Set<PatientDetail> patientDetails,
			Set<BloodBottleDetail> bloodBottleDetails) {
		this.contactDetail = contactDetail;
		this.bloodGroup = bloodGroup;
		this.donatedTimes = donatedTimes;
		this.isSpecialDonor = isSpecialDonor;
		this.donationDate = donationDate;
		this.donorRandomId = donorRandomId;
		this.weight = weight;
		this.bloodPressure = bloodPressure;
		this.pulse = pulse;
		this.hemoglobin = hemoglobin;
		this.patientDetails = patientDetails;
		this.bloodBottleDetails = bloodBottleDetails;
	}

	public Integer getDonorId() {
		return this.donorId;
	}

	public void setDonorId(Integer donorId) {
		this.donorId = donorId;
	}

	public ContactDetail getContactDetail() {
		return this.contactDetail;
	}

	public void setContactDetail(ContactDetail contactDetail) {
		this.contactDetail = contactDetail;
	}

	public String getBloodGroup() {
		return this.bloodGroup;
	}

	public void setBloodGroup(String bloodGroup) {
		this.bloodGroup = bloodGroup;
	}

	public Integer getDonatedTimes() {
		return this.donatedTimes;
	}

	public void setDonatedTimes(Integer donatedTimes) {
		this.donatedTimes = donatedTimes;
	}

	public String getIsSpecialDonor() {
		return this.isSpecialDonor;
	}

	public void setIsSpecialDonor(String isSpecialDonor) {
		this.isSpecialDonor = isSpecialDonor;
	}

	public String getDonationDate() {
		return this.donationDate;
	}

	public void setDonationDate(String donationDate) {
		this.donationDate = donationDate;
	}

	public String getDonorRandomId() {
		return this.donorRandomId;
	}

	public void setDonorRandomId(String donorRandomId) {
		this.donorRandomId = donorRandomId;
	}

	public Integer getWeight() {
		return this.weight;
	}

	public void setWeight(Integer weight) {
		this.weight = weight;
	}

	public String getBloodPressure() {
		return this.bloodPressure;
	}

	public void setBloodPressure(String bloodPressure) {
		this.bloodPressure = bloodPressure;
	}

	public Integer getPulse() {
		return this.pulse;
	}

	public void setPulse(Integer pulse) {
		this.pulse = pulse;
	}

	public String getHemoglobin() {
		return this.hemoglobin;
	}

	public void setHemoglobin(String hemoglobin) {
		this.hemoglobin = hemoglobin;
	}

	public Set<PatientDetail> getPatientDetails() {
		return this.patientDetails;
	}

	public void setPatientDetails(Set<PatientDetail> patientDetails) {
		this.patientDetails = patientDetails;
	}

	public Set<BloodBottleDetail> getBloodBottleDetails() {
		return this.bloodBottleDetails;
	}

	public void setBloodBottleDetails(Set<BloodBottleDetail> bloodBottleDetails) {
		this.bloodBottleDetails = bloodBottleDetails;
	}

}
