package com.bloodbank.model;

// Generated Mar 16, 2013 12:03:45 PM by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

/**
 * EventDetail generated by hbm2java
 */
public class EventDetail implements java.io.Serializable {

	private Integer eventId;
	private String eventTitle;
	private String eventDate;

	private String eventVanue;
	private String eventDescription;
	private Integer eventIncharge;
	private Integer eventCollection;
	private Set<CommentDetail> commentDetails = new HashSet<CommentDetail>(0);
	private Set<BloodBottleDetail> bloodBottleDetails = new HashSet<BloodBottleDetail>(
			0);
	private Set<StaffDetail> eventStaffDetails = new HashSet<StaffDetail>(0);
	public EventDetail() {
	}

	public EventDetail(String eventTitle, String eventDate, String eventTime,
			String eventVanue, String eventDescription, Integer eventIncharge,
			Integer eventCollection, Set<CommentDetail> commentDetails,
			Set<BloodBottleDetail> bloodBottleDetails,
			Set<StaffDetail> eventStaffDetails) {
		this.eventTitle = eventTitle;
		this.eventDate = eventDate;
		
		this.eventVanue = eventVanue;
		this.eventDescription = eventDescription;
		this.eventIncharge = eventIncharge;
		this.eventCollection = eventCollection;
		this.commentDetails = commentDetails;
		this.bloodBottleDetails = bloodBottleDetails;
		this.eventStaffDetails = eventStaffDetails;
	}

	public Integer getEventId() {
		return this.eventId;
	}

	public void setEventId(Integer eventId) {
		this.eventId = eventId;
	}

	public String getEventTitle() {
		return this.eventTitle;
	}

	public void setEventTitle(String eventTitle) {
		this.eventTitle = eventTitle;
	}

	public String getEventDate() {
		return this.eventDate;
	}

	public void setEventDate(String eventDate) {
		this.eventDate = eventDate;
	}



	public String getEventVanue() {
		return this.eventVanue;
	}

	public void setEventVanue(String eventVanue) {
		this.eventVanue = eventVanue;
	}

	public String getEventDescription() {
		return this.eventDescription;
	}

	public void setEventDescription(String eventDescription) {
		this.eventDescription = eventDescription;
	}

	public Integer getEventIncharge() {
		return this.eventIncharge;
	}

	public void setEventIncharge(Integer eventIncharge) {
		this.eventIncharge = eventIncharge;
	}

	public Integer getEventCollection() {
		return this.eventCollection;
	}

	public void setEventCollection(Integer eventCollection) {
		this.eventCollection = eventCollection;
	}

	public Set<CommentDetail> getCommentDetails() {
		return this.commentDetails;
	}

	public void setCommentDetails(Set<CommentDetail> commentDetails) {
		this.commentDetails = commentDetails;
	}

	public Set<BloodBottleDetail> getBloodBottleDetails() {
		return this.bloodBottleDetails;
	}

	public void setBloodBottleDetails(Set<BloodBottleDetail> bloodBottleDetails) {
		this.bloodBottleDetails = bloodBottleDetails;
	}

	public Set<StaffDetail> getEventStaffDetails() {
		return this.eventStaffDetails;
	}

	public void setEventStaffDetails(Set<StaffDetail> eventStaffDetails) {
		this.eventStaffDetails = eventStaffDetails;
	}

}
