package com.bloodbank.model;

// Generated Mar 16, 2013 12:03:45 PM by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

/**
 * HospitalDetail generated by hbm2java
 */
public class HospitalDetail implements java.io.Serializable {

	private Integer HId;
	private String HName;
	private String HAddress;
	private Set<IssueDetail> issueDetails = new HashSet<IssueDetail>(0);

	public HospitalDetail() {
	}

	public HospitalDetail(String HName, String HAddress,
			Set<IssueDetail> issueDetails) {
		this.HName = HName;
		this.HAddress = HAddress;
		this.issueDetails = issueDetails;
	}

	public Integer getHId() {
		return this.HId;
	}

	public void setHId(Integer HId) {
		this.HId = HId;
	}

	public String getHName() {
		return this.HName;
	}

	public void setHName(String HName) {
		this.HName = HName;
	}

	public String getHAddress() {
		return this.HAddress;
	}

	public void setHAddress(String HAddress) {
		this.HAddress = HAddress;
	}

	public Set<IssueDetail> getIssueDetails() {
		return this.issueDetails;
	}

	public void setIssueDetails(Set<IssueDetail> issueDetails) {
		this.issueDetails = issueDetails;
	}

}
