package com.bloodbank.model;

// Generated Mar 16, 2013 12:03:45 PM by Hibernate Tools 3.3.0.GA

/**
 * InventoryDetail generated by hbm2java
 */
public class InventoryDetail implements java.io.Serializable {

	private String bloodGroup;
	private int bottlesAvailable;

	public InventoryDetail() {
	}

	public InventoryDetail(String bloodGroup, int bottlesAvailable) {
		this.bloodGroup = bloodGroup;
		this.bottlesAvailable = bottlesAvailable;
	}

	public String getBloodGroup() {
		return this.bloodGroup;
	}

	public void setBloodGroup(String bloodGroup) {
		this.bloodGroup = bloodGroup;
	}

	public int getBottlesAvailable() {
		return this.bottlesAvailable;
	}

	public void setBottlesAvailable(int bottlesAvailable) {
		this.bottlesAvailable = bottlesAvailable;
	}

}
