package com.bloodbank.model;

// Generated Mar 16, 2013 12:03:45 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * IssueDetail generated by hbm2java
 */
public class IssueDetail implements java.io.Serializable {

	private Integer issueId;
	private PatientDetail patientDetail;
	private HospitalDetail hospitalDetail;
	private Date issueDate;
	private Integer noOfBottles;
	private String bloodGroup;

	public IssueDetail() {
	}

	public IssueDetail(PatientDetail patientDetail,
			HospitalDetail hospitalDetail, Date issueDate, Integer noOfBottles,
			String bloodGroup) {
		this.patientDetail = patientDetail;
		this.hospitalDetail = hospitalDetail;
		this.issueDate = issueDate;
		this.noOfBottles = noOfBottles;
		this.bloodGroup = bloodGroup;
	}

	public Integer getIssueId() {
		return this.issueId;
	}

	public void setIssueId(Integer issueId) {
		this.issueId = issueId;
	}

	public PatientDetail getPatientDetail() {
		return this.patientDetail;
	}

	public void setPatientDetail(PatientDetail patientDetail) {
		this.patientDetail = patientDetail;
	}

	public HospitalDetail getHospitalDetail() {
		return this.hospitalDetail;
	}

	public void setHospitalDetail(HospitalDetail hospitalDetail) {
		this.hospitalDetail = hospitalDetail;
	}

	public Date getIssueDate() {
		return this.issueDate;
	}

	public void setIssueDate(Date issueDate) {
		this.issueDate = issueDate;
	}

	public Integer getNoOfBottles() {
		return this.noOfBottles;
	}

	public void setNoOfBottles(Integer noOfBottles) {
		this.noOfBottles = noOfBottles;
	}

	public String getBloodGroup() {
		return this.bloodGroup;
	}

	public void setBloodGroup(String bloodGroup) {
		this.bloodGroup = bloodGroup;
	}

}
