package com.bloodbank.model;

// Generated Mar 16, 2013 12:03:45 PM by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

/**
 * UserDetail generated by hbm2java
 */
public class UserDetail implements java.io.Serializable {

	private Integer userId;
	private ContactDetail contactDetail;
	private String creationDate;
	private String isDonor;
	private Set<CommentDetail> commentDetails = new HashSet<CommentDetail>(0);
	private Set<AccountDetail> accountDetails = new HashSet<AccountDetail>(0);

	public UserDetail() {
	}

	public UserDetail(ContactDetail contactDetail, String creationDate,
			String isDonor, Set<CommentDetail> commentDetails,
			Set<AccountDetail> accountDetails) {
		this.contactDetail = contactDetail;
		this.creationDate = creationDate;
		this.isDonor = isDonor;
		this.commentDetails = commentDetails;
		this.accountDetails = accountDetails;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public ContactDetail getContactDetail() {
		return this.contactDetail;
	}

	public void setContactDetail(ContactDetail contactDetail) {
		this.contactDetail = contactDetail;
	}

	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	public String getIsDonor() {
		return this.isDonor;
	}

	public void setIsDonor(String isDonor) {
		this.isDonor = isDonor;
	}

	public Set<CommentDetail> getCommentDetails() {
		return this.commentDetails;
	}

	public void setCommentDetails(Set<CommentDetail> commentDetails) {
		this.commentDetails = commentDetails;
	}

	public Set<AccountDetail> getAccountDetails() {
		return this.accountDetails;
	}

	public void setAccountDetails(Set<AccountDetail> accountDetails) {
		this.accountDetails = accountDetails;
	}

}
